### ISSUE TITLE
Add new plots to a figure in MakieWidget

### ISSUE THREAD

**Issue by ZegCricket** [JuliaGtk/Gtk4Makie.jl#14] opened 2023-12-18 11:51 UTC
Hello! I was experimenting with the library and wanted to replicate the examples/interactive.jl (adding new random plots to the figure) but for the case where I want to use the MakieWidget. 

I am able to empty the figure and to change xlims! and ylims! by pressing a button, but, for some reason, it is not possible to add a new plot to it.

Here you can see the example I was trying to run:
```using Gtk4
using Gtk4Makie

box = GtkBox(:v)
button = GtkButton("click me")
label  = GtkMakieWidget()
push!(box, button)
push!(box, label)
win = GtkWindow(box, "Callbacks")

f = Figure()
ax = Axis(f[1, 1])
lines!(ax, rand(10))

push!(label, f)

scatter!(ax, rand(100))

function button_cb(widgetptr::Ptr, user_data)
     xlims!(user_data, 0, 100)
     empty!(user_data)
     scatter!(user_data, rand(100))
     nothing                  
end

signal_connect(button_cb, button, "clicked", Nothing, (), false, (ax))```

**Comment by jwahlstrand** [comment] 2023-12-18 12:25
You're right, that's totally broken! I have been using Observable inputs to create dynamic plots, but that only lets you do so much. Changing the figure in the widget should be possible too. I'll fix it ASAP.

**Comment by ZegCricket** [comment] 2023-12-18 13:02
Thank you for the quick reply! I was hoping that I was doing something wrong, since I'm quite new at Julia and Gtk4. But in this case I'll wait for the fix.
Thank you once again!

**Comment by jwahlstrand** [comment] 2024-12-27 03:24
I finally have a potential fix for this. Adding a call to `make_current` at the beginning of the callback, like the following, seems to fix the issue:
```
function button_cb(widgetptr::Ptr, user_data)
     Gtk4.make_current(label)
     xlims!(user_data, 0, 100)
     empty!(user_data)
     scatter!(user_data, rand(100))
     nothing
end
```

I think the issue is that when you call (at least some) functions that modify Makie plots, Makie expects to have a GL context. In GLMakie that happens automatically but here we have to make the widget's context current. I modified the "widgets.jl" example.

**Comment by jwahlstrand** [comment] 2024-12-29 15:49
I'm going to close this since `make_current` seems to robustly fix it. Please reopen if you still see the issue.

**Closed as completed by jwahlstrand** 2024-12-29 15:49 UTC
